/* Full reviewer journey: seven pages, language transitions, retained inputs and downloads. */
module.exports=async({p,check,out,assert,path,width,language})=>{
const pause=()=>p.waitForTimeout(300);
const navigate=async view=>{if(width===390&&!await p.locator('.sidebar').isVisible())await p.locator('#mobile-nav-toggle').click();await p.locator(`.nav-item[data-view="${view}"]`).click();await p.locator(`#view-${view}.active`).waitFor();await pause()};
const englishLeaks=async selector=>p.locator(selector).evaluateAll(roots=>{const leaks=[];for(const root of roots){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){const el=n.parentElement;if(!el.getClientRects().length||el.closest('script,style,svg,[data-v16-language]'))continue;const text=n.textContent.trim();if(/[\u0621-\u064a]/.test(text))leaks.push(text.slice(0,140))}for(const el of root.querySelectorAll('input,select,textarea,button'))if(el.getClientRects().length)for(const attr of ['placeholder','aria-label'])if(/[\u0621-\u064a]/.test(el.getAttribute(attr)||''))leaks.push(el.getAttribute(attr))}return leaks});
const locale=async expected=>{if(await p.locator('html').getAttribute('lang')!==expected){await p.locator('#lang-toggle').click();await pause()}};
await check(`${language}/${width}: scenario values survive language changes`,async()=>{const values=await p.locator('#v07-budget,#v07-gapday-cost,#v07-cost-hire,#hire-range').evaluateAll(es=>es.map(e=>[e.id,e.value]));await locale(language==='ar'?'en':'ar');await locale(language);assert.deepEqual(await p.locator('#v07-budget,#v07-gapday-cost,#v07-cost-hire,#hire-range').evaluateAll(es=>es.map(e=>[e.id,e.value])),values)});
for(const view of ['dashboard','signals','gaps','occupations','data','scenario','audit']){
 await navigate(view);
 await check(`${language}/${width}/${view}: single active page and no viewport overflow`,async()=>{assert.equal(await p.locator('.view.active').count(),1);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1))});
 await check(`${language}/${width}/${view}: English survives a live language transition`,async()=>{await locale('en');assert.deepEqual(await englishLeaks('.view.active,.topbar,.sidebar'),[]);await locale('ar');assert(/[\u0621-\u064a]/.test(await p.locator('.view.active h2').first().innerText()));await locale(language)});
 if(width===1366||width===390)await p.screenshot({path:path.join(out,`${view}-review-${language}-${width}.png`),fullPage:true});
}
await check(`${language}/${width}: audit filter uses stable record types across language switches`,async()=>{await p.locator('#v11-audit-kind').selectOption('surveillance_alert');const count=await p.locator('#audit-body tr:visible').count();assert(count>0);await locale(language==='ar'?'en':'ar');assert.equal(await p.locator('#v11-audit-kind').inputValue(),'surveillance_alert');assert.equal(await p.locator('#audit-body tr:visible').count(),count);await locale(language);await p.locator('#v11-audit-kind').selectOption('')});
await check(`${language}/${width}: audit labels have readable typography`,async()=>{const sizes=await p.locator('#view-audit .audit-trust span,#view-audit .provenance-row strong,#view-audit .ai-boundary p').evaluateAll(es=>es.map(e=>parseFloat(getComputedStyle(e).fontSize)));assert(sizes.length>0);assert(Math.min(...sizes)>=12,JSON.stringify(sizes))});
if(width>1000)await check(`${language}/${width}: sidebar has no horizontal scrollbar`,async()=>assert(await p.locator('.sidebar').evaluate(e=>e.scrollWidth<=e.clientWidth+1)));
await check(`${language}/${width}: audit CSV downloads populated records`,async()=>{const [dl]=await Promise.all([p.waitForEvent('download'),p.locator('#export-audit').click()]);assert(/\.csv$/.test(dl.suggestedFilename()));await dl.saveAs(path.join(out,`audit-${language}-${width}.csv`))});
await check(`${language}/${width}: tour can change language and close with Escape`,async()=>{await p.locator('#v11-tour-btn').click();await p.locator('#v11-tour-overlay [data-v16-language]').click();await pause();assert(await p.locator('#v11-tour-overlay.open').count());if(await p.locator('html').getAttribute('lang')==='en')assert.deepEqual(await englishLeaks('#v11-tour-overlay'),[]);await p.keyboard.press('Escape');assert.equal(await p.locator('#v11-tour-overlay.open').count(),0);await locale(language)});
await check(`${language}/${width}: executive brief updates in place`,async()=>{await p.locator('#v07-brief-btn').click();await p.locator('#v07-brief-overlay [data-v16-language]').click();await pause();assert(await p.locator('#v07-brief-overlay.open').count());if(await p.locator('html').getAttribute('lang')==='en')assert.deepEqual(await englishLeaks('#v07-brief-overlay'),[]);await p.keyboard.press('Escape');assert.equal(await p.locator('#v07-brief-overlay.open').count(),0);await locale(language)});
await check(`${language}/${width}: reviewer draft survives language switching and exports`,async()=>{await p.locator('#v16-trial-guide>summary').click();await p.locator('[data-v16-review]').click();await p.locator('[data-rpage="feedback"]').click();await p.locator('#kh-r-role').fill('QA Reviewer');await p.locator('#kh-r-must').fill('Validate decision assumptions with the HR team.');await p.locator('#kh-r-use').selectOption('maybe');await p.locator('#kh-review-overlay [data-v16-language]').click();await pause();assert(await p.locator('#kh-review-overlay.open').count());assert.equal(await p.locator('#kh-r-role').inputValue(),'QA Reviewer');assert.equal(await p.locator('#kh-r-use').inputValue(),'maybe');await p.locator('#kh-save-review').click();const [dl]=await Promise.all([p.waitForEvent('download'),p.locator('#kh-export-json').click()]);const file=path.join(out,`review-${language}-${width}.json`);await dl.saveAs(file);const review=JSON.parse(require('fs').readFileSync(file,'utf8'));assert.equal(review.reviews.at(-1).reviewer.role,'QA Reviewer');assert.equal(review.reviews.at(-1).use_intent,'maybe');for(const tab of ['score','method','evidence','feedback','pilot']){await p.locator(`[data-rpage="${tab}"]`).click();if(await p.locator('html').getAttribute('lang')==='en')assert.deepEqual(await englishLeaks('.kh-review-page.active,.kh-review-head,.kh-review-tabs'),[])}if(width===1366)await p.screenshot({path:path.join(out,`reviewer-${language}-${width}.png`)});await p.keyboard.press('Escape');assert.equal(await p.locator('#kh-review-overlay.open').count(),0);await locale(language)});
await check(`${language}/${width}: overview and expert trial are navigable`,async()=>{await p.locator('#v12-overview-btn').click();await p.locator('#v16-difference').waitFor();assert(await p.locator('.v16-comparison').innerText());assert.equal(await p.locator('.v16-source-note a').count(),3);await p.locator('[data-v16-start]').click();assert(await p.locator('#view-dashboard.active').count());assert(await p.locator('#v16-trial-guide').getAttribute('open')!==null);await p.locator('#v16-trial-guide [data-v16-view="scenario"]').click();assert(await p.locator('#view-scenario.active').count());assert.equal(await p.locator('.scenario-controls').evaluate(e=>getComputedStyle(e).direction),language==='ar'?'rtl':'ltr')});
};
