/* Full reviewer journey: seven pages, language transitions, retained inputs and downloads. */
module.exports=async({p,check,out,assert,path,width,language})=>{
const pause=()=>p.waitForTimeout(300);
const navigate=async view=>{if(width===390&&!await p.locator('.sidebar').isVisible())await p.locator('#mobile-nav-toggle').click();await p.locator(`.nav-item[data-view="${view}"]`).click();await p.locator(`#view-${view}.active`).waitFor();await pause()};
const englishLeaks=async selector=>p.locator(selector).evaluateAll(roots=>{const leaks=[];for(const root of roots){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){const el=n.parentElement;if(!el.getClientRects().length||el.closest('script,style,svg,[data-v16-language]'))continue;const text=n.textContent.trim();if(/[\u0621-\u064a]/.test(text))leaks.push(text.slice(0,140))}for(const el of root.querySelectorAll('input,select,textarea,button'))if(el.getClientRects().length)for(const attr of ['placeholder','aria-label'])if(/[\u0621-\u064a]/.test(el.getAttribute(attr)||''))leaks.push(el.getAttribute(attr))}return leaks});
const locale=async expected=>{if(await p.locator('html').getAttribute('lang')!==expected){await p.locator('#lang-toggle').click();await pause()}};
await check(`${language}/${width}: scenario values survive language changes`,async()=>{const values=await p.locator('#v07-budget,#v07-gapday-cost,#v07-cost-hire,#hire-range').evaluateAll(es=>es.map(e=>[e.id,e.value]));await locale(language==='ar'?'en':'ar');await locale(language);assert.deepEqual(await p.locator('#v07-budget,#v07-gapday-cost,#v07-cost-hire,#hire-range').evaluateAll(es=>es.map(e=>[e.id,e.value])),values)});
for(const view of ['dashboard','signals','gaps','occupations','data','scenario','audit']){
 await navigate(view);
 await check(`${language}/${width}/${view}: single active page and no viewport overflow`,async()=>{assert.equal(await p.locator('.view.active').count(),1);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1))});
 await check(`${language}/${width}/${view}: English survives a live language transition`,async()=>{await locale('en');assert.deepEqual(await englishLeaks('.view.active,.topbar,.sidebar'),[]);await locale('ar');assert(/[\u0621-\u064a]/.test(await p.locator('.view.active h2').first().innerText()));await locale(language)});
 if(width===1366||width===390)await p.screenshot({path:path.join(out,`${view}-review-${language}-${width}.png`),fullPage:true});
}
await check(`${language}/${width}: audit filter uses stable record types across language switches`,async()=>{await p.locator('#v11-audit-kind').selectOption('surveillance_alert');const count=await p.locator('#audit-body tr:visible').count();assert(count>0);await locale(language==='ar'?'en':'ar');assert.equal(await p.locator('#v11-audit-kind').inputValue(),'surveillance_alert');assert.equal(await p.locator('#audit-body tr:visible').count(),count);await locale(language);await p.locator('#v11-audit-kind').selectOption('')});
await check(`${language}/${width}: audit labels have readable typography`,async()=>{const sizes=await p.locator('#view-audit .audit-trust span,#view-audit .provenance-row strong,#view-audit .ai-boundary p').evaluateAll(es=>es.map(e=>parseFloat(getComputedStyle(e).fontSize)));assert(sizes.length>0);assert(Math.min(...sizes)>=12,JSON.stringify(sizes))});
if(width>1000)await check(`${language}/${width}: sidebar has no horizontal scrollbar`,async()=>assert(await p.locator('.sidebar').evaluate(e=>e.scrollWidth<=e.clientWidth+1),JSON.stringify(await p.locator('.sidebar').evaluate(e=>({client:e.clientWidth,scroll:e.scrollWidth,children:[...e.children].map(c=>({class:c.className,width:c.getBoundingClientRect().width,left:c.getBoundingClientRect().left}))})))));
await check(`${language}/${width}: audit CSV downloads populated records`,async()=>{const [dl]=await Promise.all([p.waitForEvent('download'),p.locator('#export-audit').click()]);assert(/\.csv$/.test(dl.suggestedFilename()));await dl.saveAs(path.join(out,`audit-${language}-${width}.csv`))});
await check(`${language}/${width}: tour can change language and close with Escape`,async()=>{await p.locator('#v11-tour-btn').click();await p.locator('#v11-tour-overlay [data-v16-language]').click();await pause();assert(await p.locator('#v11-tour-overlay.open').count());if(await p.locator('html').getAttribute('lang')==='en')assert.deepEqual(await englishLeaks('#v11-tour-overlay'),[]);await p.keyboard.press('Escape');assert.equal(await p.locator('#v11-tour-overlay.open').count(),0);await locale(language)});
await p.keyboard.press('Escape');await locale(language);
await check(`${language}/${width}: executive brief updates in place`,async()=>{await p.locator('#v07-brief-btn').click();await p.locator('#v07-brief-overlay [data-v16-language]').click();await pause();assert(await p.locator('#v07-brief-overlay.open').count());if(await p.locator('html').getAttribute('lang')==='en')assert.deepEqual(await englishLeaks('#v07-brief-overlay'),[]);await p.keyboard.press('Escape');assert.equal(await p.locator('#v07-brief-overlay.open').count(),0);await locale(language)});
await p.keyboard.press('Escape');await locale(language);
await check(`${language}/${width}: reviewer draft survives language switching and exports`,async()=>{if(await p.locator('#v16-trial-guide').getAttribute('open')===null)await p.locator('#v16-trial-guide>summary').click();await p.locator('[data-v16-review]').click();await p.locator('[data-rpage="feedback"]').click();await p.locator('#kh-r-role').fill('QA Reviewer');await p.locator('#kh-r-must').fill('Validate decision assumptions with the HR team.');await p.locator('#kh-r-use').selectOption('maybe');await p.locator('#kh-review-overlay [data-v16-language]').click();await pause();assert(await p.locator('#kh-review-overlay.open').count());assert.equal(await p.locator('#kh-r-role').inputValue(),'QA Reviewer');assert.equal(await p.locator('#kh-r-use').inputValue(),'maybe');await p.locator('#kh-save-review').click();const [dl]=await Promise.all([p.waitForEvent('download'),p.locator('#kh-export-json').click()]);const file=path.join(out,`review-${language}-${width}.json`);await dl.saveAs(file);const review=JSON.parse(require('fs').readFileSync(file,'utf8'));assert.equal(review.reviews.at(-1).reviewer.role,'QA Reviewer');assert.equal(review.reviews.at(-1).use_intent,'maybe');for(const tab of ['score','method','evidence','feedback','pilot']){await p.locator(`[data-rpage="${tab}"]`).click();if(await p.locator('html').getAttribute('lang')==='en')assert.deepEqual(await englishLeaks('.kh-review-page.active,.kh-review-head,.kh-review-tabs'),[])}if(width===1366)await p.screenshot({path:path.join(out,`reviewer-${language}-${width}.png`)});await p.keyboard.press('Escape');assert.equal(await p.locator('#kh-review-overlay.open').count(),0);await locale(language)});
await p.keyboard.press('Escape');await locale(language);
if(width===1366){
 await navigate('data');
 await check(`${language}/${width}: bad CSV is rejected without replacing the dataset`,async()=>{const before=await p.locator('#snapshot-mode').innerText();await p.locator('#csv-upload').setInputFiles({name:'invalid.csv',mimeType:'text/csv',buffer:Buffer.from('wrong,columns\nnot,a-snapshot')});await pause();assert(/لم يمر|did not pass/.test(await p.locator('#import-result').innerText()));assert.equal(await p.locator('#snapshot-mode').innerText(),before)});
 await check(`${language}/${width}: valid snapshot gates event analysis until events are imported`,async()=>{await p.locator('#csv-upload').setInputFiles(path.resolve(__dirname,'../sample_position_snapshot_v11.csv'));await pause();assert(/مستورد|Local|Imported/i.test(await p.locator('#snapshot-mode').innerText()));assert.equal(await p.locator('#v07-cost-hire').inputValue(),'');assert.equal(await p.locator('#v07-approval-hire').inputValue(),'');assert(/موقوف|Gated/i.test(await p.locator('#event-mode').innerText()));await p.locator('#event-upload').setInputFiles(path.resolve(__dirname,'../sample_hr_event_log_v11.csv'));await pause();assert(/مستورد|Local|Imported/i.test(await p.locator('#event-mode').innerText()));await locale('en');assert.deepEqual(await englishLeaks('#view-data'),[]);await locale('ar');assert(/مقبول/.test(await p.locator('#import-result').innerText()));await locale(language)});
 await check(`${language}/${width}: demo reset restores a usable starting point`,async()=>{await p.locator('#reset-demo').click();await pause();assert(/تركيبي|Synthetic/i.test(await p.locator('#snapshot-mode').innerText()));assert(/تركيبي|Synthetic/i.test(await p.locator('#event-mode').innerText()));assert.equal(await p.locator('#import-result').innerText(),'')});
}
await check(`${language}/${width}: overview and expert trial are navigable`,async()=>{await p.locator('#v12-overview-btn').click();await p.locator('#v16-difference').waitFor();assert(await p.locator('.v16-comparison').innerText());assert.equal(await p.locator('.v16-comparison').evaluate(e=>getComputedStyle(e).direction),language==='ar'?'rtl':'ltr');assert.equal(await p.locator('.v16-source-note a').count(),3);await p.locator('[data-v16-start]').click();assert(await p.locator('#view-dashboard.active').count());assert(await p.locator('#v16-trial-guide').getAttribute('open')!==null);await p.locator('#v16-trial-guide [data-v16-view="scenario"]').click();assert(await p.locator('#view-scenario.active').count());assert.equal(await p.locator('.scenario-controls').evaluate(e=>getComputedStyle(e).direction),language==='ar'?'rtl':'ltr')});
await check(`${language}/${width}: per-cell costs and zero-day overrides survive sector and language changes`,async()=>{
 await navigate('scenario');if(await p.locator('#v14-advanced').getAttribute('open')===null)await p.locator('#v14-advanced>summary').click();if(await p.locator('#v07-reality-panel').getAttribute('open')===null)await p.locator('#v07-reality-panel>summary').click();
 await p.locator('#v07-cost-hire').fill('54321');await p.locator('#v07-approval-hire').fill('0');await p.locator('#sector-select').selectOption('HLT');await pause();assert.equal(await p.locator('#v07-cost-hire').inputValue(),'220000');assert.equal(await p.locator('#v07-approval-hire').inputValue(),'45');await p.locator('#sector-select').selectOption('EDU');await pause();assert.equal(await p.locator('#v07-cost-hire').inputValue(),'54321');assert.equal(await p.locator('#v07-approval-hire').inputValue(),'0');await locale(language==='ar'?'en':'ar');assert.equal(await p.locator('#v07-cost-hire').inputValue(),'54321');assert.equal(await p.locator('#v07-approval-hire').inputValue(),'0');await locale(language);
});
await check(`${language}/${width}: next-day recommendation loads a testable action`,async()=>{await navigate('dashboard');const card=await p.locator('#v16-next-action').boundingBox();if(width>1000)assert(card.y<300);assert(await p.locator('.v16-action-detail').innerText());await p.locator('#v16-next-evidence').click();assert(await p.locator('#detail-drawer.open').count());await p.locator('#drawer-close').click();await p.locator('#v16-try-next').click();await pause();assert(await p.locator('#view-scenario.active').count());assert.equal(await p.locator('#scenario-cell').inputValue(),'demo-001');assert(Number(await p.locator('#transfer-range').inputValue())>0);assert(await p.locator('#scenario-donor').inputValue())});
await check(`${language}/${width}: Arabic cards use Arabic rate terminology`,async()=>{await locale('ar');await navigate('signals');assert(!/FTE-mo|INCIDENCE|PREVALENCE/.test(await p.locator('#signals-grid').innerText()));await navigate('dashboard');assert(!/FTE-mo|INCIDENCE|PREVALENCE/.test(await p.locator('#executive-metrics').innerText()));await locale(language)});
await check(`${language}/${width}: audit searches occupation and location with combined filters`,async()=>{await navigate('audit');await p.locator('#v11-audit-search').fill('الجوف إنذار');await pause();assert(await p.locator('#audit-body tr:visible').count()>0);await p.locator('#v16-audit-sector').selectOption('HLT');assert.equal(await p.locator('#audit-body tr:visible').count(),0);assert(await p.locator('#v16-audit-empty').isVisible());await p.locator('#v16-audit-clear').click();assert(await p.locator('#audit-body tr:visible').count()>0);const day=await p.locator('#audit-body tr[data-audit-date]').first().getAttribute('data-audit-date');await p.locator('#v16-audit-from').fill(day);await p.locator('#v16-audit-to').fill(day);await p.locator('#v16-audit-to').press('Tab');await p.locator('#v16-audit-order').selectOption('oldest');const times=await p.locator('#audit-body tr:visible').evaluateAll(es=>es.map(e=>Number(e.dataset.auditTime)));assert(times.length>0);assert(times.every((t,i)=>!i||t>=times[i-1]));await locale(language==='ar'?'en':'ar');assert.equal(await p.locator('#v16-audit-from').inputValue(),day);assert.equal(await p.locator('#v16-audit-order').inputValue(),'oldest');await locale(language);await p.locator('#v16-audit-from').fill('2099-01-01');await p.locator('#v16-audit-from').press('Tab');assert.equal(await p.locator('#audit-body tr:visible').count(),0);assert(await p.locator('#v16-audit-empty').isVisible());await p.locator('#v16-audit-clear').click();if(width===1366||width===390)await p.screenshot({path:path.join(out,`audit-final-${language}-${width}.png`),fullPage:true})});
await check(`${language}/${width}: navigation labels are visible without opt-in`,async()=>{if(width===390)await p.locator('#mobile-nav-toggle').click();const names=p.locator('.nav-item>span:not(.nav-icon)');assert.equal(await names.count(),7);for(const item of await names.all())assert(await item.isVisible());assert(!await p.locator('#v11-sidebar-toggle').isVisible());if(width===390)await p.locator('.nav-item[data-view="dashboard"]').click()});
if(width===1366)await check(`${language}/${width}: shareable language links and reload preference work`,async()=>{await p.goto('http://127.0.0.1:8077/?lang=en&qa=1');await pause();assert.equal(await p.locator('html').getAttribute('lang'),'en');await p.locator('#lang-toggle').click();await pause();await p.reload();await pause();assert.equal(await p.locator('html').getAttribute('lang'),'ar');await locale(language)});
};
