function init(){populateSectorSelectors();bindNav();bindLanguage();bindSearch();bindCsv();bindEventCsv();bindGo();bindCatalogSearch();renderAll()}
function applyI18n(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';$$('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));$$('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));$('#lang-toggle').textContent=lang==='ar'?'EN':'AR'}
function populateSectorSelectors(){['sector-select','decoder-sector'].forEach(id=>{const el=$('#'+id),old=el.value||activeSector;el.innerHTML='';Object.entries(CONFIG.sectors).forEach(([k,c])=>el.add(new Option(c[lang],k)));el.value=CONFIG.sectors[old]?old:activeSector});$('#sector-select').onchange=e=>{activeSector=e.target.value;$('#decoder-sector').value=activeSector;fillDecoder();renderAll()};$('#decoder-sector').onchange=e=>{activeSector=e.target.value;$('#sector-select').value=activeSector;fillDecoder();renderAll()}}
function bindNav(){$$('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view))}
function bindGo(){$$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go))}
function showView(view){$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$$('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+view));$('#page-title').textContent=t('pages.'+view);if(view==='ssco')renderSsco();if(view==='surveillance')renderSurveillance()}
function bindLanguage(){$('#lang-toggle').onclick=()=>{lang=lang==='ar'?'en':'ar';populateSectorSelectors();renderAll();const active=$('.view.active')?.id.replace('view-','')||'dashboard';$('#page-title').textContent=t('pages.'+active)}}
function renderAll(){applyI18n();renderDashboard();renderSsco();fillDecoder();renderPrevalence();renderSurveillance();renderCriticality();renderDataState()}
function renderDashboard(){const rows=currentRows(),needed=rows.reduce((a,r)=>a+Number(r.needed),0),filled=rows.reduce((a,r)=>a+Number(r.filled),0),gap=Math.max(0,needed-filled),svs=rows.map(surveillanceFor).filter(Boolean),alerts=svs.filter(x=>x.alert).length,inc=svs.reduce((a,x)=>a+x.current,0);$('#hero-critical-count').textContent=fmt(rows.filter(r=>priority(r)>=70).length);$('#metric-grid').innerHTML=[[lang==='ar'?'القدرة المطلوبة':'Required capacity',fmt(needed),'position_snapshot'],[lang==='ar'?'الفجوة الحالية':'Current gap',fmt(gap),`${fmt(needed?gap/needed*100:0,1)}%`],['Incidence',eventMode==='gated'?'—':fmt(inc),eventMode==='gated'?'hr_event_log required':CURRENT_MONTH],[lang==='ar'?'إنذارات نشطة':'Active alerts',eventMode==='gated'?'—':fmt(alerts),`≥ ${ALERT_MULTIPLIER}× baseline`]].map(m=>`<article class="metric-card"><span class="metric-label">${m[0]}</span><strong>${m[1]}</strong><small>${m[2]}</small></article>`).join('');const ranked=[...rows].sort((a,b)=>priority(b)-priority(a));$('#priority-list').innerHTML=ranked.slice(0,4).map(r=>{const s=priority(r),sv=surveillanceFor(r);return`<div class="priority-row"><div class="priority-name"><strong>${occupationLabel(r.ssco)}</strong><small>SSCO ${r.ssco} · ${sectorCfg(r.sector).locations.find(x=>x.id===r.location)?.[lang]}</small></div><div class="mini-bar"><i style="width:${s}%"></i></div><span class="score-pill score-${scoreClass(s)}">${s}/100</span>${sv?.alert?'<span class="alert-dot">●</span>':''}<button class="explain-btn" data-explain="${r.source_row}">${t('explain')}</button></div>`}).join('');bindExplain();$('#coverage-block').innerHTML=[['position_snapshot',100],['SSCO 2024 mapping',100],['priority factors',100],['hr_event_log',eventMode==='gated'?0:100]].map(([l,p])=>coverageItem(l,p)).join('');$('#data-status').querySelector('span:last-child').textContent=(snapshotMode==='synthetic'&&eventMode==='synthetic')?t('synthetic'):(lang==='ar'?'بيانات محلية':'Local data')}
function coverageItem(label,pct){return`<div class="coverage-item"><div class="coverage-line"><span>${label}</span><strong>${pct}%</strong></div><div class="coverage-track"><i style="width:${pct}%"></i></div></div>`}
function renderSsco(){const q=($('#ssco-search')?.value||'').trim().toLowerCase(),rows=SSCO_CATALOG.filter(o=>(o.code+' '+o.ar+' '+o.en).toLowerCase().includes(q));$('#ssco-meta').innerHTML=`<div><span>${t('ssco_source')}</span><strong>${lang==='ar'?SSCO_META.authorityAr:SSCO_META.authorityEn}</strong></div><div><span>${t('ssco_version')}</span><strong>Master Sheets ${SSCO_META.version}</strong></div><div><span>${t('ssco_checked')}</span><strong>${SSCO_META.checkedOn}</strong></div><div><span>${t('ssco_catalog_status')}</span><strong>${SSCO_CATALOG.length} demo occupations</strong></div>`;$('#ssco-body').innerHTML=rows.map(o=>`<tr><td class="code-cell">${o.code}</td><td><strong>${o[lang]}</strong><small class="subline">${lang==='ar'?o.en:o.ar}</small></td><td>${o.major}</td><td>${o.submajor}</td><td>${o.subgroup}</td><td>${o.unit}</td><td>${sectorCfg(o.sector)?.[lang]||o.sector}</td></tr>`).join('')||'<tr><td colspan="7">—</td></tr>';$('#ssco-source-link').href=SSCO_META.sourceUrl}
function bindCatalogSearch(){$('#ssco-search')?.addEventListener('input',renderSsco)}
function fillDecoder(){const c=sectorCfg(activeSector);$('#decoder-sector').value=activeSector;fillSelect($('#decoder-location'),c.locations);const occs=relevantOccupations(activeSector).map(o=>({id:o.code,ar:`${o.code} — ${o.ar}`,en:`${o.code} — ${o.en}`}));fillSelect($('#decoder-ssco-select'),occs);fillSelect($('#decoder-level'),c.levels);fillSelect($('#decoder-category'),c.categories);$('#decoder-level-label').textContent=c.levelLabel[lang];$('#decoder-category-label').textContent=c.categoryLabel[lang];['decoder-location','decoder-ssco-select','decoder-level','decoder-category'].forEach(id=>$('#'+id).onchange=()=>{syncLevelFromOccupation();renderDecoder()});syncLevelFromOccupation();renderDecoder()}
function fillSelect(el,arr){const prev=el.value;el.innerHTML='';arr.forEach(x=>el.add(new Option(x[lang],x.id)));if(arr.some(x=>x.id===prev))el.value=prev}
function syncLevelFromOccupation(){const o=sscoByCode($('#decoder-ssco-select').value);if(activeSector==='EDU'&&o?.level){$('#decoder-level').value=o.level;$('#decoder-level').disabled=true}else $('#decoder-level').disabled=false}
function renderDecoder(){const r={sector:activeSector,location:$('#decoder-location').value,ssco:$('#decoder-ssco-select').value,level:$('#decoder-level').value,category:$('#decoder-category').value};$('#decoder-code').textContent=cellCode(r);$('#decoder-identity').textContent=identity(r);const o=sscoByCode(r.ssco);$('#decoder-ssco').textContent=o?`${o.code} — ${o[lang]}`:'—';$('#decoder-hierarchy').textContent=o?`${t('major')} ${o.major} · ${t('submajor')} ${o.submajor} · ${t('subgroup')} ${o.subgroup} · ${t('unit')} ${o.unit}`:'';const match=SNAPSHOTS.find(x=>cellCode(x)===cellCode(r));$('#decoder-match').innerHTML=match?`✓ ${t('match_found')} ${t('needed')}: <strong>${match.needed}</strong> · ${t('filled')}: <strong>${match.filled}</strong>`:t('no_match')}
function renderPrevalence(){const q=($('#prevalence-search')?.value||'').trim().toLowerCase(),rows=currentRows().filter(r=>(cellCode(r)+' '+identity(r)+' '+r.ssco).toLowerCase().includes(q));$('#prevalence-body').innerHTML=rows.map(r=>{const g=deficit(r),dr=deficitRatio(r)*100;return`<tr><td class="code-cell">${cellCode(r)}</td><td><strong>${occupationLabel(r.ssco)}</strong><small class="subline">SSCO ${r.ssco}</small></td><td>${fmt(r.needed)}</td><td>${fmt(r.filled)}</td><td class="${g>0?'gap-negative':'gap-positive'}">${fmt(g)}</td><td>${fmt(dr,1)}%</td><td><code>${r.source_row}</code></td></tr>`}).join('')||'<tr><td colspan="7">—</td></tr>'}
function bindSearch(){$('#prevalence-search').addEventListener('input',renderPrevalence)}
function renderSurveillance(){const rows=currentRows();if(eventMode==='gated'){$('#surveillance-gate').hidden=false;$('#surveillance-grid').innerHTML='';return}else $('#surveillance-gate').hidden=true;$('#surveillance-grid').innerHTML=rows.map(r=>{const s=surveillanceFor(r),state=s.alert?'high':s.monitor?'med':'low',label=s.alert?t('alert_high'):s.monitor?t('monitor'):t('normal'),ratio=!Number.isFinite(s.ratio)?'∞':`${fmt(s.ratio,1)}×`,causes=s.causes.map(([k,v])=>`${causeLabel(k)} ${v}`).join(' · ')||'—';return`<article class="surveillance-card ${state}"><div class="surv-head"><div><h3>${occupationLabel(r.ssco)}</h3><small>SSCO ${r.ssco} · ${sectorCfg(r.sector).locations.find(x=>x.id===r.location)?.[lang]}</small></div><span class="signal-badge ${state}">${label}</span></div><div class="surv-metrics"><div><span>${t('current_incidence')}</span><strong>${s.current}</strong></div><div><span>${t('baseline')}</span><strong>${fmt(s.baseline,1)}/mo</strong></div><div><span>${t('ratio')}</span><strong>${ratio}</strong></div></div><p class="cause-line"><b>${t('causes')}:</b> ${causes}</p><div class="trend-mini">${s.hist.map(v=>`<i style="height:${Math.max(8,v*14)}px" title="${v}"></i>`).join('')}<i class="current" style="height:${Math.max(8,s.current*14)}px" title="${s.current}"></i></div></article>`}).join('')}
function causeLabel(k){const ar={resignation:'استقالة',retirement:'تقاعد',transfer_out:'نقل خارج',position_created_unfilled:'استحداث غير مشغول',demand_increase:'زيادة طلب'},en={resignation:'resignation',retirement:'retirement',transfer_out:'transfer-out',position_created_unfilled:'unfilled new position',demand_increase:'demand increase'};return(lang==='ar'?ar:en)[k]||k}
function renderCriticality(){const rows=[...currentRows()].sort((a,b)=>priority(b)-priority(a));$('#criticality-grid').innerHTML=rows.map(r=>{const s=priority(r),cls=scoreClass(s),b=burden(r),cfg=sectorCfg(r.sector),sv=surveillanceFor(r);return`<article class="criticality-card ${cls}"><div class="crit-top"><div><h3>${occupationLabel(r.ssco)}</h3><small>SSCO ${r.ssco} · ${cfg.locations.find(x=>x.id===r.location)?.[lang]}</small></div><div class="crit-score">${s}</div></div><div class="factor-grid"><div class="factor"><span>${t('deficit')}</span><strong>${fmt(deficit(r))} / ${fmt(r.needed)}</strong></div><div class="factor"><span>${t('avg_vacancy')}</span><strong>${fmt(r.avgVacancyWeeks)} w</strong></div><div class="factor"><span>${t('scarcity')}</span><strong>${r.scarcity}/3</strong></div><div class="factor"><span>${t('substitute')}</span><strong>${r.substitutes}/2</strong></div></div><div class="crit-bottom"><span class="tag">${t('burden')}: ${fmt(b,1)} ${cfg.burdenUnit[lang]}</span>${sv?.alert?'<span class="tag warn">Surveillance +15</span>':''}<button class="explain-btn" data-explain="${r.source_row}">${t('explain')}</button></div></article>`}).join('');bindExplain()}
function bindExplain(){$$('[data-explain]').forEach(b=>b.onclick=()=>openExplain(b.dataset.explain))}
function openExplain(id){const r=SNAPSHOTS.find(x=>x.source_row===id);if(!r)return;const sv=surveillanceFor(r),o=sscoByCode(r.ssco);$('#explain-title').textContent=`${occupationLabel(r.ssco)} — ${priority(r)}/100`;$('#explain-content').innerHTML=`<table class="explain-table"><tbody><tr><td>SSCO</td><td><code>${r.ssco}</code> — ${o?.[lang]||''}</td></tr><tr><td>${t('source_row')}</td><td><code>${r.source_row}</code></td></tr><tr><td>${t('deficit_ratio')}</td><td>${fmt(deficitRatio(r)*100,1)}%</td></tr><tr><td>${t('scarcity')}</td><td>${r.scarcity}/3</td></tr><tr><td>${t('avg_vacancy')}</td><td>${r.avgVacancyWeeks} weeks</td></tr><tr><td>${t('substitute')}</td><td>${r.substitutes}/2</td></tr><tr><td>${t('criticality')}</td><td>${r.criticality}/3</td></tr><tr><td>${t('burden')}</td><td>${fmt(burden(r),1)} ${sectorCfg(r.sector).burdenUnit[lang]}</td></tr><tr><td>Surveillance</td><td>${sv?`${sv.current} vs ${fmt(sv.baseline,1)}/mo · ${sv.alert?'ALERT':sv.monitor?'MONITOR':'NORMAL'}`:'GATED'}</td></tr><tr><td>${t('formula_version')}</td><td><code>KHP-v0.2</code></td></tr></tbody></table><div class="explain-formula">base_score = 100 × (0.30×deficit_ratio + 0.20×scarcity_norm + 0.15×vacancy_duration_norm + 0.15×substitution_risk + 0.20×service_criticality_norm)<br><br>surveillance adjustment = +15 when an alert is active, +6 when monitoring. Alert: current-period gap-onset events ≥ 2 and current/baseline ≥ ${ALERT_MULTIPLIER}×. Incidence is calculated only from dated HR events, never from snapshot deltas.</div>`;$('#explain-dialog').showModal()}
function renderDataState(){$('#snapshot-mode').textContent=snapshotMode==='synthetic'?(lang==='ar'?'تجريبي':'synthetic'):(lang==='ar'?'مستورد محليًا':'local import');$('#event-mode').textContent=eventMode==='synthetic'?(lang==='ar'?'تجريبي':'synthetic'):eventMode==='local'?(lang==='ar'?'مستورد محليًا':'local import'):(lang==='ar'?'موقوف':'gated');$('#event-gate-note').textContent=eventMode==='gated'?t('event_gated'):''}
function bindCsv(){$('#csv-upload').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const parsed=parseCsv(await f.text()),req=['source_row','sector','location','ssco','level','category','needed','filled','scarcity','substitutes','avgVacancyWeeks','criticality','affectedUnits'];if(!parsed.length||req.some(k=>!(k in parsed[0])))throw 0;SNAPSHOTS=parsed.map(r=>({...r,needed:+r.needed,filled:+r.filled,scarcity:+r.scarcity,substitutes:+r.substitutes,avgVacancyWeeks:+r.avgVacancyWeeks,criticality:+r.criticality,affectedUnits:+r.affectedUnits}));snapshotMode='local';HR_EVENTS=[];eventMode='gated';activeSector=SNAPSHOTS[0].sector||activeSector;populateSectorSelectors();$('#import-result').textContent=`✓ ${parsed.length} ${t('rows_loaded')}`;renderAll()}catch{$('#import-result').textContent=t('invalid_csv')}})}
function bindEventCsv(){$('#event-upload').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const parsed=parseCsv(await f.text()),req=['event_id','position_id','event_type','event_date','sector','location','ssco','level','category'];if(!parsed.length||req.some(k=>!(k in parsed[0])))throw 0;HR_EVENTS=parsed;eventMode='local';$('#event-import-result').textContent=`✓ ${parsed.length} ${t('rows_loaded')}`;renderAll()}catch{$('#event-import-result').textContent=t('invalid_csv')}})}
function parseCsv(text){const lines=text.trim().split(/\r?\n/),headers=splitCsvLine(lines.shift());return lines.filter(Boolean).map(line=>{const vals=splitCsvLine(line);return Object.fromEntries(headers.map((h,i)=>[h.trim(),(vals[i]??'').trim()]))})}
function splitCsvLine(line){let out=[],cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===','&&!q){out.push(cur);cur=''}else cur+=ch}out.push(cur);return out}
document.addEventListener('DOMContentLoaded',init);
