const I18N={
 ar:{
  pages:{dashboard:'مركز القيادة',signals:'الإنذار المبكر',scenario:'مختبر السيناريو',gaps:'فجوات القوى العاملة',occupations:'المهن والتصنيف',data:'مركز البيانات',audit:'الذاكرة المؤسسية'},
  nav:{command:'القرار',analysis:'التحليل',system:'النظام'},eyebrow:'WORKFORCE EARLY-WARNING INFRASTRUCTURE',sector:'القطاع',synthetic:'بيانات تجريبية',
  system:{engine:'محرك القياس',demo:'نسخة عامة ببيانات تركيبية. لا يوجد اتصال فعلي ببيانات جهة حكومية.'},
  home:{kicker:'WORKFORCE COMMAND CENTER',headline:'راقب نبض القوى العاملة قبل أن تتحول الفجوة إلى أزمة.',subhead:'Kinetic HR لا ينتظر تقرير الشواغر. يقيس نشوء الفجوات عبر الزمن، يكتشف التغير غير الطبيعي، ويرتب أين يجب أن يبدأ التدخل — بنتائج ثابتة وقابلة للتدقيق.',reviewSignals:'راجع الإشارات الحرجة',runScenario:'اختبر قرارًا',normalized:'مهن موحدة',eventBased:'Incidence حقيقي',reproducible:'نتائج قابلة للإعادة',activeSignals:'إشارات نشطة',pulseTitle:'هل سرعة نشوء الفجوات تتغير؟',pulseDesc:'إجمالي أحداث الفجوة الجديدة في القطاع خلال الأشهر الأخيرة، محسوبة من سجل الأحداث المؤرخ فقط.',queueTitle:'ما الذي يحتاج قرارًا الآن؟',hotspotsTitle:'أعلى نقاط ضغط القدرة',integrityTitle:'القياس مستقل عن الـLLM',integrityDesc:'الأرقام والتنبيهات تنتج من أحداث مؤرخة وقواعد ثابتة ومُصدّرة بإصدار محدد. يمكن للذكاء الاصطناعي شرحها، لكنه ليس مصدرها.',openAudit:'افتح سجل التدقيق →',required:'القدرة المطلوبة',coverage:'التغطية الحالية',gap:'الفجوة الحالية',incidence:'أحداث الفجوة هذا الشهر',alerts:'إنذارات نشطة'},
  common:{viewAll:'عرض الكل',details:'التفاصيل',simulate:'اختبر سيناريو',normal:'طبيعي',monitor:'مراقبة',alert:'إنذار'},
  signals:{title:'الإنذار المبكر',desc:'كل إشارة مرتبطة بخط أساس خاص بالمهنة والموقع. لا يوجد threshold عالمي واحد يخفي الاختلافات المحلية.',all:'الكل',alerts:'إنذار',monitor:'مراقبة',normal:'طبيعي',current:'الحالي',baseline:'الخط الأساسي',ratio:'التغير',priority:'الأولوية',causes:'أسباب الحدث',noEvents:'يلزم سجل أحداث مؤرخ ومتوافق لتشغيل Surveillance.'},
  gaps:{title:'فجوات القوى العاملة الحالية',desc:'Prevalence: المطلوب مقابل المشغول الآن. هذه شاشة المخزون الحالي، ولا تُستخدم لاستنتاج Incidence.',search:'ابحث بالمهنة أو الموقع أو رمز SSCO',all:'الكل',deficitOnly:'العجز فقط',criticalOnly:'الأولوية العالية',occupation:'المهنة',location:'الموقع',needed:'المطلوب',filled:'المشغول',gap:'الفجوة',duration:'مدة الشغور',priority:'الأولوية',coverage:'نسبة التغطية',totalGap:'إجمالي العجز',highPriority:'عالية الأولوية',burden:'عبء التعرض'},
  scenario:{title:'مختبر السيناريو',desc:'اختبر أثر التوظيف أو النقل أو إعادة التأهيل أو التغطية المؤقتة قبل اتخاذ القرار. لا يوجد write-back إلى نظام المصدر في هذه النسخة.',noWriteback:'محاكاة فقط · No write-back',chooseCell:'اختر الخلية المهنية',hire:'توظيف جديد',transfer:'نقل داخلي للداخل',upskill:'إعادة تأهيل / Upskill',contract:'تغطية مؤقتة',reset:'إعادة ضبط',save:'حفظ السيناريو',resultTitle:'الأثر المتوقع على القدرة',note:'هذه المحاكاة تقيس أثر الوحدات المضافة على الفجوة والعبء والأولوية فقط. لا تحسب تكلفة مالية ما لم تتوفر بيانات تكلفة موثقة من الجهة.',savedTitle:'سيناريوهات محفوظة',baselineGap:'الفجوة الحالية',afterGap:'الفجوة بعد التدخل',burdenReduction:'خفض العبء',priorityAfter:'الأولوية بعد',capacityAdded:'قدرة مضافة',saved:'تم حفظ السيناريو في الذاكرة المؤسسية المحلية.'},
  occupations:{title:'المهن والتصنيف السعودي الموحد',desc:'SSCO هو العمود الفقري للمقارنة بين المسميات الداخلية. Kinetic HR يحتفظ بمعرّف الوظيفة مستقلًا عن خلية التحليل.',search:'ابحث بالرمز أو المسمى',source:'المصدر المرجعي',openSource:'فتح GASTAT ↗',occupation:'المهنة',hierarchy:'التسلسل',location:'الموقع',cellTitle:'تركيب خلية مهنية',cellDesc:'الخلية تجمع وظائف متشابهة للتحليل؛ ليست Position ID ولا تستبدله.',generated:'WORKFORCE CELL CODE',disclaimer:'الكتالوج المدمج في النسخة العامة هو مجموعة موثقة تستخدمها بيانات العرض، وليس بديلًا عن ملف GASTAT الكامل. بنية النظام جاهزة لاستيراد Master Sheet الكامل.'},
  data:{title:'مركز البيانات والتكامل',desc:'المنتج مصمم كطبقة Read-only فوق SAP أو Oracle أو أي HRMS قائم. البيانات التشغيلية تبقى في نظام الجهة.',readOnly:'READ-ONLY BY DESIGN',connectorReady:'نمط تكامل مدعوم',contractBased:'عبر عقد بيانات قياسي',notConnected:'غير متصل في النسخة العامة',uploadSnapshot:'استيراد Snapshot',uploadEvents:'استيراد Event Log',contractTitle:'حالة عقد البيانات',snapshot:'Stock / Prevalence',events:'Flow / Incidence',ssco:'SSCO mapping',audit:'Provenance / Audit',ready:'جاهز',gated:'موقوف',local:'مستورد محليًا',synthetic:'تركيبي',resetDemo:'إعادة البيانات التجريبية',downloadSample:'تحميل ملف نموذجي'},
  audit:{title:'الذاكرة المؤسسية وسجل التدقيق',desc:'الفرق بين تحليل لحظي ونظام تشغيلي: كل حالة لها بصمة، مصدر، إصدار معادلة، وسياسة ترصد يمكن إعادة إنتاجها لاحقًا.',export:'تصدير السجل CSV',provenance:'حالة المصدر والمنهج',aiTitle:'الذكاء الاصطناعي يشرح الإشارة ولا يصنع القياس',aiDesc:'يمكن لأي LLM تفسير النتيجة، لكن Kinetic HR يحفظ التاريخ التشغيلي، الـbaseline، الإصدار، والمصدر الذي أنتج الرقم.',ledger:'السجل القابل للإعادة',when:'الوقت',type:'النوع',cell:'الخلية',detail:'التفاصيل',basis:'الأساس',source:'المصدر',note:'في النسخة العامة تُخزن metadata غير حساسة محليًا في المتصفح. في النشر المؤسسي ينتقل السجل إلى قاعدة بيانات الجهة مع RBAC وسياسة احتفاظ.',ssco:'مرجع SSCO',formula:'إصدار المعادلة',policy:'سياسة الترصد',fingerprint:'بصمة الحالة',snapshot:'لقطة القوى العاملة',events:'سجل الأحداث',count:'عدد السجلات',mode:'الوضع',imported:'آخر استيراد',notImported:'غير مستورد'},
  drawer:{simulate:'فتح في مختبر السيناريو'},
  cause:{resignation:'استقالة',retirement:'تقاعد',transfer_out:'نقل خارج',position_created_unfilled:'استحداث غير مشغول',demand_increase:'زيادة طلب'}
 },
};
