function renderDataHub(){const snap=$('#snapshot-mode'),ev=$('#event-mode');snap.textContent=snapshotMode==='synthetic'?t('data.synthetic'):t('data.local');snap.className='source-tag '+(snapshotMode==='synthetic'?'':'local');ev.textContent=eventMode==='synthetic'?t('data.synthetic'):eventMode==='local'?t('data.local'):t('data.gated');ev.className='source-tag '+(eventMode==='gated'?'gated':eventMode==='local'?'local':'');$('#event-gate-note').textContent=eventMode==='gated'?(lang==='ar'?'الإنذار المبكر موقوف حتى استيراد hr_event_log المتوافق.':'Early warning is gated until the matching hr_event_log is imported.'):'';const checks=[[t('data.snapshot'),SNAPSHOTS.length? t('data.ready'):t('data.gated'),!!SNAPSHOTS.length],[t('data.events'),eventMode==='gated'?t('data.gated'):t('data.ready'),eventMode!=='gated'],[t('data.ssco'),SSCO_CATALOG.length? t('data.ready'):t('data.gated'),!!SSCO_CATALOG.length],[t('data.audit'),stableStateFingerprint(),true]];$('#data-contract-checks').innerHTML=checks.map(([l,v,ok])=>`<div class="contract-check"><span>${l}</span><strong class="${ok?'ok':'warn'}">${esc(v)}</strong></div>`).join('')}
function bindImports(){$('#csv-upload').addEventListener('change',handleSnapshotImport);$('#event-upload').addEventListener('change',handleEventImport);$('#reset-demo').onclick=resetDemoData}

function resetDemoData(){SNAPSHOTS=DEMO_SNAPSHOTS.map(r=>({...r}));HR_EVENTS=DEMO_EVENTS.map(e=>({...e}));snapshotMode='synthetic';eventMode='synthetic';snapshotImportedAt=null;eventImportedAt=null;activeSector='EDU';selectedScenarioSource=null;populateSectorSelectors();appendAuditRecord({key:'reset|'+Date.now(),kind:'demo_reset',formula:PRIORITY_FORMULA_VERSION,fingerprint:stableStateFingerprint()});$('#import-result').textContent='';$('#event-import-result').textContent='';showToast(lang==='ar'?'تمت إعادة البيانات التجريبية.':'Demo data restored.');renderAll()}

async function handleSnapshotImport(e){const f=e.target.files?.[0];if(!f)return;try{const parsed=parseCsv(await f.text()),req=['source_row','sector','location','ssco','level','category','needed','filled','scarcity','substitutes','avgVacancyWeeks','criticality','affectedUnits'];if(!parsed.length||req.some(k=>!(k in parsed[0])))throw 0;SNAPSHOTS=parsed.map(r=>({...r,needed:+r.needed,filled:+r.filled,scarcity:+r.scarcity,substitutes:+r.substitutes,avgVacancyWeeks:+r.avgVacancyWeeks,criticality:+r.criticality,affectedUnits:+r.affectedUnits}));snapshotMode='local';snapshotImportedAt=new Date().toISOString();HR_EVENTS=[];eventMode='gated';eventImportedAt=null;activeSector=SNAPSHOTS[0].sector||activeSector;selectedScenarioSource=null;populateSectorSelectors();recordImportAudit('snapshot',parsed.length,f.name);$('#import-result').textContent=`✓ ${parsed.length} rows`;renderAll()}catch{$('#import-result').textContent=lang==='ar'?'تعذر قراءة الملف أو الحقول المطلوبة ناقصة.':'Could not read file or required fields are missing.'}}
async function handleEventImport(e){const f=e.target.files?.[0];if(!f)return;try{const parsed=parseCsv(await f.text()),req=['event_id','position_id','event_type','event_date','sector','location','ssco','level','category'];if(!parsed.length||req.some(k=>!(k in parsed[0])))throw 0;HR_EVENTS=parsed;eventMode='local';eventImportedAt=new Date().toISOString();recordImportAudit('events',parsed.length,f.name);$('#event-import-result').textContent=`✓ ${parsed.length} rows`;renderAll()}catch{$('#event-import-result').textContent=lang==='ar'?'تعذر قراءة الملف أو الحقول المطلوبة ناقصة.':'Could not read file or required fields are missing.'}}
function parseCsv(text){const lines=text.trim().split(/\r?\n/),headers=splitCsvLine(lines.shift());return lines.filter(Boolean).map(line=>{const vals=splitCsvLine(line);return Object.fromEntries(headers.map((h,i)=>[h.trim(),(vals[i]??'').trim()]))})}
function splitCsvLine(line){let out=[],cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===','&&!q){out.push(cur);cur=''}else cur+=ch}out.push(cur);return out}

function renderAudit(){const a=auditState();const trust=[[t('audit.ssco'),`${a.sscoVersion} · ${a.sscoMode}`,'GASTAT'],[t('audit.formula'),a.formula,'deterministic'],[t('audit.policy'),`≥ ${a.threshold}× baseline`,'event-based'],[t('audit.fingerprint'),a.fingerprint,a.contract]];$('#audit-trust-grid').innerHTML=trust.map(([l,v,n])=>`<article class="audit-trust"><span>${l}</span><strong>${esc(v)}</strong><small>${n}</small></article>`).join('');$('#audit-fingerprint').textContent=a.fingerprint;$('#audit-provenance').innerHTML=`<div class="provenance-row"><div><span>${t('audit.snapshot')}</span><strong>${t('audit.count')}: ${a.snapshotCount}</strong></div><div><span>${t('audit.mode')}</span><code>${a.snapshotMode}</code></div><div><span>${t('audit.imported')}</span><strong>${a.snapshotImportedAt?new Date(a.snapshotImportedAt).toLocaleString(lang==='ar'?'ar-SA':'en-GB'):t('audit.notImported')}</strong></div></div><div class="provenance-row"><div><span>${t('audit.events')}</span><strong>${t('audit.count')}: ${a.eventCount}</strong></div><div><span>${t('audit.mode')}</span><code>${a.eventMode}</code></div><div><span>${t('audit.imported')}</span><strong>${a.eventImportedAt?new Date(a.eventImportedAt).toLocaleString(lang==='ar'?'ar-SA':'en-GB'):t('audit.notImported')}</strong></div></div><div class="provenance-row"><div><span>Scenarios</span><strong>${t('audit.count')}: ${a.scenarioCount}</strong></div><div><span>${t('audit.mode')}</span><code>local-ledger</code></div><div><span>Formula</span><strong>${a.formula}</strong></div></div>`;const rows=[...a.ledger].reverse();$('#audit-body').innerHTML=rows.length?rows.map(x=>{const when=x.recorded_at?new Date(x.recorded_at).toLocaleString(lang==='ar'?'ar-SA':'en-GB'):'—';let detail='—',basis=x.formula||'—',source=x.file_name||x.event_mode||x.snapshot_mode||x.source_row||'—';if(x.kind==='surveillance_alert')detail=`ALERT · ${x.current}/${x.baseline} · ${x.ratio==null?'∞':x.ratio+'×'}`;else if(x.kind==='scenario_saved')detail=x.detail||x.scenario_id;else if(x.count)detail=`${x.count} rows`;return `<tr><td>${when}</td><td>${esc(x.kind||'—')}</td><td><code>${esc(x.cell||'—')}</code></td><td>${esc(detail)}</td><td>${esc(basis)}</td><td><code>${esc(source)}</code></td></tr>`}).join(''):'<tr><td colspan="6">—</td></tr>'}
function bindAuditExport(){$('#export-audit').onclick=()=>{const rows=readAuditLedger();const headers=['recorded_at','kind','cell','ssco','detail','formula','source_row','file_name','fingerprint'];const csv=[headers.join(','),...rows.map(r=>headers.map(h=>`"${String(r[h]??'').replace(/"/g,'""')}"`).join(','))].join('\n');downloadBlob(csv,'kinetic-hr-audit.csv','text/csv');showToast(lang==='ar'?'تم تصدير السجل.':'Audit ledger exported.') }}
function downloadBlob(text,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();URL.revokeObjectURL(a.href);a.remove()}

function bindDetailButtons(){document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>openDrawer(b.dataset.detail))}
function bindDrawer(){$('#drawer-close').onclick=closeDrawer;$('#drawer-backdrop').onclick=closeDrawer;$('#drawer-scenario').onclick=()=>{const id=$('#detail-drawer').dataset.source;selectedScenarioSource=id;closeDrawer();showView('scenario')}}
function openDrawer(id){const r=getRowBySource(id);if(!r)return;const sv=surveillanceFor(r),st=signalState(r),ratio=sv?(!Number.isFinite(sv.ratio)?'∞':`${fmt(sv.ratio,1)}×`):'—';$('#detail-drawer').dataset.source=id;$('#drawer-title').textContent=occupationLabel(r.ssco);$('#drawer-content').innerHTML=`<div class="drawer-section"><h4>${lang==='ar'?'الحالة التشغيلية':'Operational state'}</h4><div class="trace-grid"><div class="trace-stat"><span>SSCO</span><strong>${r.ssco}</strong></div><div class="trace-stat"><span>${t('gaps.location')}</span><strong>${esc(sectorCfg(r.sector).locations.find(x=>x.id===r.location)?.[lang]||'')}</strong></div><div class="trace-stat"><span>${t('gaps.gap')}</span><strong>${deficit(r)} / ${r.needed}</strong></div><div class="trace-stat"><span>${t('gaps.priority')}</span><strong>${priority(r)}/100</strong></div><div class="trace-stat"><span>Incidence</span><strong>${sv?sv.current:'GATED'}</strong></div><div class="trace-stat"><span>Baseline</span><strong>${sv?fmt(sv.baseline,1):'—'}</strong></div><div class="trace-stat"><span>Ratio</span><strong>${ratio}</strong></div><div class="trace-stat"><span>Signal</span><strong>${st.toUpperCase()}</strong></div></div></div><div class="drawer-section"><h4>${lang==='ar'?'قابلية التتبع':'Traceability'}</h4><div class="trace-grid"><div class="trace-stat"><span>source_row</span><strong>${esc(r.source_row)}</strong></div><div class="trace-stat"><span>workforce_cell</span><strong>${esc(cellCode(r))}</strong></div><div class="trace-stat"><span>formula</span><strong>${PRIORITY_FORMULA_VERSION}</strong></div><div class="trace-stat"><span>fingerprint</span><strong>${stableStateFingerprint()}</strong></div></div></div><div class="drawer-section"><h4>${lang==='ar'?'منطق القياس':'Measurement logic'}</h4><div class="formula-block">base = 100 × (0.30×deficit + 0.20×scarcity + 0.15×duration + 0.15×substitution risk + 0.20×service criticality)\n\nsurveillance = +15 alert / +6 monitor\n\nIncidence source = dated HR events only\nSnapshot delta ≠ Incidence</div></div>`;$('#drawer-backdrop').classList.add('open');$('#detail-drawer').classList.add('open');$('#detail-drawer').setAttribute('aria-hidden','false')}
function closeDrawer(){$('#drawer-backdrop').classList.remove('open');$('#detail-drawer').classList.remove('open');$('#detail-drawer').setAttribute('aria-hidden','true')}
function showToast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(showToast._t);showToast._t=setTimeout(()=>el.classList.remove('show'),2200)}

document.addEventListener('DOMContentLoaded',init);
