Object.assign(I18N,{
 en:{
  pages:{dashboard:'Command Center',signals:'Early Warning',scenario:'Scenario Lab',gaps:'Workforce Gaps',occupations:'Occupations & SSCO',data:'Data Hub',audit:'Institutional Memory'},
  nav:{command:'Command',analysis:'Analysis',system:'System'},eyebrow:'WORKFORCE EARLY-WARNING INFRASTRUCTURE',sector:'Sector',synthetic:'Synthetic data',
  system:{engine:'Measurement engine',demo:'Public demonstration with synthetic data. No live government data connection.'},
  home:{kicker:'WORKFORCE COMMAND CENTER',headline:'See workforce deterioration before it becomes an operational crisis.',subhead:'Kinetic HR does not wait for a vacancy report. It measures new gap events over time, detects abnormal change, and prioritizes where intervention should start — with deterministic, auditable outputs.',reviewSignals:'Review critical signals',runScenario:'Test a decision',normalized:'Normalized occupations',eventBased:'True incidence',reproducible:'Reproducible outputs',activeSignals:'Active signals',pulseTitle:'Is gap incidence accelerating?',pulseDesc:'New gap-onset events in the sector over recent months, calculated only from the dated event log.',queueTitle:'What needs a decision now?',hotspotsTitle:'Highest capacity pressure',integrityTitle:'Measurement independent of the LLM',integrityDesc:'Metrics and alerts come from dated events, versioned deterministic rules, and traceable sources. AI may explain them; it does not generate the measurement.',openAudit:'Open audit trail →',required:'Required capacity',coverage:'Current coverage',gap:'Current gap',incidence:'Gap events this month',alerts:'Active alerts'},
  common:{viewAll:'View all',details:'Details',simulate:'Run scenario',normal:'Normal',monitor:'Monitor',alert:'Alert'},
  signals:{title:'Early warning',desc:'Every signal is compared with its own occupation-location baseline. There is no single global threshold that hides local differences.',all:'All',alerts:'Alerts',monitor:'Monitor',normal:'Normal',current:'Current',baseline:'Baseline',ratio:'Change',priority:'Priority',causes:'Event causes',noEvents:'A dated, matching HR event log is required to run Surveillance.'},
  gaps:{title:'Current workforce gaps',desc:'Prevalence: required versus filled capacity now. This is the stock view and is never used to infer Incidence.',search:'Search occupation, location or SSCO',all:'All',deficitOnly:'Deficit only',criticalOnly:'High priority',occupation:'Occupation',location:'Location',needed:'Needed',filled:'Filled',gap:'Gap',duration:'Vacancy age',priority:'Priority',coverage:'Coverage rate',totalGap:'Total deficit',highPriority:'High priority',burden:'Exposure burden'},
  scenario:{title:'Scenario lab',desc:'Test the effect of hiring, internal transfer, upskilling, or temporary coverage before a decision is made. No write-back to the source system in this release.',noWriteback:'SIMULATION ONLY · NO WRITE-BACK',chooseCell:'Choose workforce cell',hire:'New hires',transfer:'Internal transfer-in',upskill:'Upskill / reskill',contract:'Temporary coverage',reset:'Reset',save:'Save scenario',resultTitle:'Expected capacity impact',note:'This simulation measures the effect of added capacity on gap, burden, and priority only. It does not estimate monetary cost unless verified cost data are provided by the entity.',savedTitle:'Saved scenarios',baselineGap:'Baseline gap',afterGap:'Gap after intervention',burdenReduction:'Burden reduction',priorityAfter:'Priority after',capacityAdded:'Capacity added',saved:'Scenario saved to local institutional memory.'},
  occupations:{title:'Occupations & Saudi Standard Classification',desc:'SSCO is the comparison backbone across internal job titles. Kinetic HR keeps the individual Position ID separate from the analytical workforce cell.',search:'Search code or occupation title',source:'Reference source',openSource:'Open GASTAT ↗',occupation:'Occupation',hierarchy:'Hierarchy',location:'Location',cellTitle:'Compose a workforce cell',cellDesc:'The cell groups comparable positions for analysis; it is not a Position ID and does not replace one.',generated:'WORKFORCE CELL CODE',disclaimer:'The built-in public-demo catalog is the validated subset used by the demo data; it does not replace GASTAT’s full master sheet. The schema is ready to ingest the full master sheet.'},
  data:{title:'Data hub & integration',desc:'Designed as a read-only intelligence layer above SAP, Oracle, or any existing HRMS. Operational records remain in the entity source system.',readOnly:'READ-ONLY BY DESIGN',connectorReady:'Supported integration pattern',contractBased:'Via standard data contract',notConnected:'Not connected in public demo',uploadSnapshot:'Import snapshot CSV',uploadEvents:'Import event log CSV',contractTitle:'Data contract state',snapshot:'Stock / Prevalence',events:'Flow / Incidence',ssco:'SSCO mapping',audit:'Provenance / Audit',ready:'Ready',gated:'Gated',local:'Local import',synthetic:'Synthetic',resetDemo:'Reset demo data',downloadSample:'Download sample'},
  audit:{title:'Institutional memory & audit trail',desc:'The difference between one-off analysis and operational infrastructure: every state has a fingerprint, source, formula version, and surveillance policy that can be reproduced later.',export:'Export ledger CSV',provenance:'Source & method state',aiTitle:'AI explains the signal; it does not create the measurement',aiDesc:'An LLM can interpret the output, but Kinetic HR retains the operational history, baseline, version, and source that produced the number.',ledger:'Reproducible ledger',when:'Recorded',type:'Type',cell:'Cell',detail:'Detail',basis:'Basis',source:'Source',note:'This public release stores non-sensitive metadata locally in the browser. Institutional deployment moves the ledger to the entity database with RBAC and retention policy.',ssco:'SSCO reference',formula:'Formula version',policy:'Surveillance policy',fingerprint:'State fingerprint',snapshot:'Workforce snapshot',events:'HR event log',count:'Record count',mode:'Mode',imported:'Last import',notImported:'Not imported'},
  drawer:{simulate:'Open in scenario lab'},
  cause:{resignation:'resignation',retirement:'retirement',transfer_out:'transfer-out',position_created_unfilled:'unfilled new position',demand_increase:'demand increase'}
 }
});
