let signalFilter='all',gapFilter='all',selectedScenarioSource=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function init(){
 populateSectorSelectors();bindNav();bindLanguage();bindSignalFilters();bindGapFilters();bindSearch();bindImports();bindScenario();bindDrawer();bindAuditExport();renderAll();
}
function applyI18n(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));$('#lang-toggle').textContent=lang==='ar'?'EN':'AR'}
function populateSectorSelectors(){
 ['sector-select','decoder-sector'].forEach(id=>{const el=$('#'+id);if(!el)return;const old=el.value||activeSector;el.innerHTML='';Object.entries(CONFIG.sectors).forEach(([k,c])=>el.add(new Option(c[lang],k)));el.value=CONFIG.sectors[old]?old:activeSector});
 $('#sector-select').onchange=e=>{activeSector=e.target.value;$('#decoder-sector').value=activeSector;selectedScenarioSource=null;renderAll()};
 $('#decoder-sector').onchange=e=>{activeSector=e.target.value;$('#sector-select').value=activeSector;fillComposer();renderAll()};
}
function bindNav(){document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go))}
function showView(view){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+view));$('#page-title').textContent=t('pages.'+view);if(view==='scenario')renderScenario();if(view==='audit')renderAudit();window.scrollTo({top:0,behavior:'smooth'})}
function bindLanguage(){$('#lang-toggle').onclick=()=>{lang=lang==='ar'?'en':'ar';populateSectorSelectors();renderAll();const active=document.querySelector('.view.active')?.id.replace('view-','')||'dashboard';$('#page-title').textContent=t('pages.'+active)}}
function renderAll(){applyI18n();renderHeader();renderDashboard();renderSignals();renderGaps();renderScenario();renderOccupations();renderDataHub();renderAudit();fillComposer();const active=document.querySelector('.view.active')?.id.replace('view-','')||'dashboard';$('#page-title').textContent=t('pages.'+active)}
function renderHeader(){const s=sectorSummary();$('#nav-alert-count').textContent=eventMode==='gated'?'':s.alerts||'';$('#data-status').querySelector('span:last-child').textContent=snapshotMode==='synthetic'?t('synthetic'):t('data.local');$('#current-period-label').textContent=CURRENT_MONTH}

function renderDashboard(){
 const s=sectorSummary();$('#hero-alerts').textContent=eventMode==='gated'?'—':s.alerts+s.monitors;
 $('#radar-points').innerHTML=s.rows.slice(0,7).map((r,i)=>{const state=signalState(r),pos=[[70,23],[25,34],[73,67],[42,72],[19,65],[58,42],[82,45]][i]||[50,50];return `<i class="radar-point ${state}" style="left:${pos[0]}%;top:${pos[1]}%"></i>`}).join('');
 const coverage=Math.min(100,s.coverage*100);const metrics=[
  [t('home.required'),fmt(s.needed),'◫','--blue','#edf3ff',`${s.rows.length} cells`],
  [t('home.coverage'),`${fmt(coverage,1)}%`,'✓','--teal','#e7f8f4',`${fmt(s.filled)} / ${fmt(s.needed)}`],
  [t('home.gap'),fmt(s.gap),'△','--red','#fff0f0',`${fmt(s.needed?100*s.gap/s.needed:0,1)}%`],
  [t('home.incidence'),eventMode==='gated'?'—':fmt(s.incidence),'↗','--amber','#fff7e8',eventMode==='gated'?'event log required':CURRENT_MONTH]
 ];
 $('#executive-metrics').innerHTML=metrics.map(([label,val,icon,color,soft,note])=>`<article class="exec-metric" style="--metric-color:var(${color});--metric-soft:${soft}"><div class="metric-top"><span>${label}</span><i class="metric-icon">${icon}</i></div><strong>${val}</strong><small>${note}</small></article>`).join('');
 renderPulse(s);renderDecisionQueue(s.rows);renderHotspots();renderIntegrity();
}
function renderPulse(summary){
 const vals=sectorIncidenceSeries(),labels=[...BASELINE_MONTHS,CURRENT_MONTH].map(x=>x.slice(5)),max=Math.max(2,...vals),w=620,h=170,pad=26,step=(w-pad*2)/(vals.length-1||1);const pts=vals.map((v,i)=>[pad+i*step,h-pad-(v/max)*(h-pad*2)]);const line=pts.map(p=>p.join(',')).join(' ');const area=`${pad},${h-pad} ${line} ${w-pad},${h-pad}`;
 let grid='';[0,.5,1].forEach(f=>{const y=pad+(h-pad*2)*f;grid+=`<line class="chart-grid-line" x1="${pad}" y1="${y}" x2="${w-pad}" y2="${y}"/>`});
 const dots=pts.map((p,i)=>`<circle class="chart-dot ${i===pts.length-1?'current':''}" cx="${p[0]}" cy="${p[1]}" r="4"/><text class="chart-value" x="${p[0]}" y="${p[1]-10}" text-anchor="middle">${vals[i]}</text><text class="chart-label" x="${p[0]}" y="${h-4}" text-anchor="middle">${labels[i]}</text>`).join('');
 $('#pulse-chart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><defs><linearGradient id="pulseFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#18c4a3" stop-opacity=".22"/><stop offset="1" stop-color="#18c4a3" stop-opacity="0"/></linearGradient></defs>${grid}<polygon class="chart-area" points="${area}"/><polyline class="chart-line" points="${line}"/>${dots}</svg>`;
 const last=vals.at(-1)||0,base=vals.slice(0,-1).reduce((a,b)=>a+b,0)/(Math.max(1,vals.length-1));const state=eventMode==='gated'?'gated':last>=base*ALERT_MULTIPLIER&&last>=2?'alert':last>base?'monitor':'normal';const pill=$('#pulse-state');pill.className='state-pill '+(state==='gated'?'':state);pill.textContent=state==='gated'?'GATED':t('common.'+state);$('#pulse-legend').innerHTML=`<span><i class="legend-dot teal"></i>${lang==='ar'?'أحداث الفجوة الجديدة':'New gap events'}</span><span><i class="legend-dot gray"></i>${lang==='ar'?'الخط التاريخي':'Historical months'}</span>`;
}
function renderDecisionQueue(rows){const ranked=[...rows].sort((a,b)=>priority(b)-priority(a));$('#decision-queue').innerHTML=ranked.slice(0,5).map(r=>{const st=signalState(r),sv=surveillanceFor(r);return `<button class="decision-item ${st}" data-detail="${esc(r.source_row)}"><i class="severity-bar"></i><span><strong>${esc(occupationLabel(r.ssco))}</strong><small>${esc(sectorCfg(r.sector).locations.find(x=>x.id===r.location)?.[lang]||'')} · ${sv?`${sv.current}/${fmt(sv.baseline,1)} ${lang==='ar'?'حدث/شهر':'events/mo'}`:'Prevalence only'}</small></span><span class="queue-score"><b>${priority(r)}</b><span>priority</span></span></button>`}).join('');bindDetailButtons()}
function renderHotspots(){const rows=locationPressure();const max=Math.max(1,...rows.map(x=>x.maxPriority));$('#hotspots-list').innerHTML=rows.slice(0,5).map(x=>`<div class="hotspot-row"><div class="label"><strong>${esc(x.label)}</strong><small>${fmt(x.gap)} ${lang==='ar'?'فجوة':'gap'} · ${fmt(x.ratio*100,1)}%</small></div><div class="risk-track"><i style="width:${Math.max(5,x.maxPriority/max*100)}%"></i></div><div class="risk-value">${x.maxPriority}</div></div>`).join('')||'<div class="empty-state">—</div>'}
function renderIntegrity(){const checks=[['SSCO',`${SSCO_META.version} · ${SSCO_META.catalogMode}`,true],['Incidence',eventMode==='gated'?'GATED':'event-based',eventMode!=='gated'],['Formula',PRIORITY_FORMULA_VERSION,true],['State',stableStateFingerprint(),true]];$('#integrity-checks').innerHTML=checks.map(([l,v,ok])=>`<div class="integrity-check"><span>${l}</span><b class="${ok?'':'warn'}">${esc(v)}</b></div>`).join('')}

function bindSignalFilters(){document.querySelectorAll('#signal-filter button').forEach(b=>b.onclick=()=>{signalFilter=b.dataset.signal;document.querySelectorAll('#signal-filter button').forEach(x=>x.classList.toggle('active',x===b));renderSignals()})}
function renderSignals(){const rows=currentRows(),states=rows.map(r=>({r,state:signalState(r),sv:surveillanceFor(r)}));const counts={alert:states.filter(x=>x.state==='alert').length,monitor:states.filter(x=>x.state==='monitor').length,normal:states.filter(x=>x.state==='normal').length};$('#signals-summary').innerHTML=[['alert',counts.alert],['monitor',counts.monitor],['normal',counts.normal]].map(([k,v])=>`<span class="summary-chip ${k}"><b>${v}</b>${t('common.'+k)}</span>`).join('');if(eventMode==='gated'){$('#signals-grid').innerHTML=`<div class="empty-state">${t('signals.noEvents')}</div>`;return}const filtered=states.filter(x=>signalFilter==='all'||x.state===signalFilter);$('#signals-grid').innerHTML=filtered.map(({r,state,sv})=>{const ratio=!Number.isFinite(sv.ratio)?'∞':`${fmt(sv.ratio,1)}×`,causes=sv.causes.map(([k,v])=>`${causeLabel(k)} ${v}`).join(' · ')||'—';return `<article class="signal-card ${state}"><div class="signal-head"><div><h3>${esc(occupationLabel(r.ssco))}</h3><small>SSCO ${r.ssco} · ${esc(sectorCfg(r.sector).locations.find(x=>x.id===r.location)?.[lang]||'')}</small></div><span class="signal-badge ${state}">${t('common.'+state)}</span></div><div class="signal-metrics"><div class="signal-metric"><span>${t('signals.current')}</span><strong>${sv.current}</strong></div><div class="signal-metric"><span>${t('signals.baseline')}</span><strong>${fmt(sv.baseline,1)}</strong></div><div class="signal-metric"><span>${t('signals.ratio')}</span><strong>${ratio}</strong></div><div class="signal-metric"><span>${t('signals.priority')}</span><strong>${priority(r)}</strong></div></div><div class="signal-causes"><b>${t('signals.causes')}:</b> ${esc(causes)}</div><div class="signal-trend">${sv.hist.map(v=>`<i style="height:${Math.max(6,v*12)}px"></i>`).join('')}<i class="current" style="height:${Math.max(6,sv.current*12)}px"></i></div><div class="signal-actions"><button data-detail="${esc(r.source_row)}">${t('common.details')} →</button><code>${esc(cellCode(r))}</code></div></article>`}).join('')||'<div class="empty-state">—</div>';bindDetailButtons()}

function bindGapFilters(){document.querySelectorAll('[data-gap-filter]').forEach(b=>b.onclick=()=>{gapFilter=b.dataset.gapFilter;document.querySelectorAll('[data-gap-filter]').forEach(x=>x.classList.toggle('active',x===b));renderGaps()})}
