const DAY=86400000,AVG_MONTH_DAYS=30.4375;
const ALLOWED_EVENT_TYPES=new Set(['resignation','retirement','transfer_out','hire','transfer_in','demand_increase','demand_decrease','position_created_unfilled','position_closed']);
const DEMAND_BASES=new Set(['approved-establishment','workload-derived','service-standard','strategic-scenario','budgeted']);
let DATA_QUALITY={snapshot:{accepted:0,quarantined:0,warnings:[],errors:[],quarantine:[]},events:{accepted:0,quarantined:0,warnings:[],errors:[],quarantine:[]}};

const t=k=>k.split('.').reduce((o,p)=>o?.[p],I18N[lang])??k;
const dUTC=s=>{if(!s)return null;const d=new Date(String(s).length===10?`${s}T00:00:00Z`:s);return Number.isNaN(d.getTime())?null:d};
const isoDate=d=>d instanceof Date&&!Number.isNaN(d)?d.toISOString().slice(0,10):'';
const addDays=(d,n)=>new Date(d.getTime()+n*DAY);
const daysBetween=(a,b)=>Math.max(0,Math.round((b-a)/DAY));
const cellCode=r=>[r.sector,r.location,r.ssco,r.level].join('-');
const occupationLabel=code=>sscoByCode(code)?.[lang]||String(code);
function identity(r){const c=sectorCfg(r.sector);return [occupationLabel(r.ssco),c?.locations.find(x=>x.id===r.location)?.[lang],c?.levels.find(x=>x.id===r.level)?.[lang],c?.categories.find(x=>x.id===r.category)?.[lang]].filter(Boolean).join(' · ')}
const requiredFte=r=>Number(r.needed_fte??r.needed??0);
const availableFte=r=>Number(r.available_fte??r.filled??0);
const deficit=r=>Math.max(0,requiredFte(r)-availableFte(r));
const surplus=r=>Math.max(0,availableFte(r)-requiredFte(r));
const deficitRatio=r=>requiredFte(r)>0?deficit(r)/requiredFte(r):0;
const matchedCoverageRow=r=>requiredFte(r)>0?Math.min(availableFte(r),requiredFte(r))/requiredFte(r):1;
const scoreClass=s=>s==null?'na':s>=70?'high':s>=45?'med':'low';
const causeLabel=k=>t('cause.'+k)===('cause.'+k)?k:t('cause.'+k);
const getRowBySource=id=>SNAPSHOTS.find(x=>x.source_row===id);
const getRowByCell=code=>SNAPSHOTS.find(x=>cellCode(x)===code);
const currentRows=()=>SNAPSHOTS.filter(r=>r.sector===activeSector);
const relevantOccupations=sector=>{const used=new Set(SNAPSHOTS.filter(r=>r.sector===sector).map(r=>String(r.ssco)));return SSCO_CATALOG.filter(o=>used.has(o.code))};

function getAsOfDate(){const snaps=SNAPSHOTS.map(r=>dUTC(r.as_of_date)).filter(Boolean);if(snaps.length)return new Date(Math.max(...snaps.map(d=>d.getTime())));const ev=HR_EVENTS.map(e=>dUTC(e.event_date)).filter(Boolean);return ev.length?new Date(Math.max(...ev.map(d=>d.getTime()))):new Date()}
function getWindows(r){const policy=window.KHPilot?KHPilot.policy(r):SURVEILLANCE,end=r?dUTC(r.as_of_date):getAsOfDate(),start=addDays(end,-(policy.windowDays-1));const baseline=[];for(let i=policy.baselineWindows;i>=1;i--){const e=addDays(start,-1-(i-1)*policy.windowDays),s=addDays(e,-(policy.windowDays-1));baseline.push({start:s,end:e})}return{current:{start,end},baseline}}
function periodLabel(){const {current}=getWindows();return `${isoDate(current.start)} → ${isoDate(current.end)}`}

function defaultEventDelta(type){if(['resignation','retirement','transfer_out'].includes(type))return{capacity:-1,demand:0};if(['hire','transfer_in'].includes(type))return{capacity:1,demand:0};if(['demand_increase','position_created_unfilled'].includes(type))return{capacity:0,demand:1};if(['demand_decrease','position_closed'].includes(type))return{capacity:0,demand:-1};return{capacity:0,demand:0}}
function normalizeEvent(e){const d=defaultEventDelta(e.event_type);return{...e,capacity_delta_fte:Number(e.capacity_delta_fte===''||e.capacity_delta_fte==null?d.capacity:e.capacity_delta_fte),demand_delta_fte:Number(e.demand_delta_fte===''||e.demand_delta_fte==null?d.demand:e.demand_delta_fte)}}
function eventsForCell(r){return HR_EVENTS.filter(e=>cellCode(e)===cellCode(r)&&dUTC(e.event_date)&&dUTC(e.event_date)<=getAsOfDate()).map(normalizeEvent).sort((a,b)=>String(a.event_date).localeCompare(String(b.event_date)))}

function replayCell(r){const events=eventsForCell(r),currNeed=requiredFte(r),currAvail=availableFte(r);const totalCap=events.reduce((a,e)=>a+Number(e.capacity_delta_fte||0),0),totalDem=events.reduce((a,e)=>a+Number(e.demand_delta_fte||0),0);let need=currNeed-totalDem,avail=currAvail-totalCap;const records=[];for(const e of events){const beforeNeed=need,beforeAvail=avail,beforeGap=Math.max(0,need-avail);need+=Number(e.demand_delta_fte||0);avail+=Number(e.capacity_delta_fte||0);const afterGap=Math.max(0,need-avail),newGapFte=Math.max(0,afterGap-beforeGap),recoveredGapFte=Math.max(0,beforeGap-afterGap);records.push({...e,beforeNeed,beforeAvail,beforeGap,afterNeed:need,afterAvail:avail,afterGap,newGapFte,recoveredGapFte,episodeOnset:beforeGap===0&&afterGap>0,resolution:beforeGap>0&&afterGap===0})}return{startNeed:currNeed-totalDem,startAvail:currAvail-totalCap,records,endNeed:need,endAvail:avail,reconciles:Math.abs(need-currNeed)<.001&&Math.abs(avail-currAvail)<.001}}
function stateBeforeDate(r,date){const rp=replayCell(r);let need=rp.startNeed,avail=rp.startAvail;for(const e of rp.records){const ed=dUTC(e.event_date);if(ed&&ed<date){need=e.afterNeed;avail=e.afterAvail}else break}return{need,avail}}
function requiredFteMonths(r,start,end){let state=stateBeforeDate(r,start),need=state.need,cursor=start,totalFteDays=0;const events=replayCell(r).records.filter(e=>{const d=dUTC(e.event_date);return d&&d>=start&&d<=end&&Number(e.demand_delta_fte||0)!==0});for(const e of events){const ed=dUTC(e.event_date),segment=Math.max(0,(ed-cursor)/DAY);totalFteDays+=need*segment;need+=Number(e.demand_delta_fte||0);cursor=ed}totalFteDays+=need*Math.max(1,(end-cursor)/DAY+1);return Math.max(0,totalFteDays/AVG_MONTH_DAYS)}
function incidenceWindow(r,start,end){const rec=replayCell(r).records.filter(e=>{const d=dUTC(e.event_date);return d&&d>=start&&d<=end});const gapRec=rec.filter(e=>e.newGapFte>0);const newGapFte=gapRec.reduce((a,e)=>a+e.newGapFte,0),denominator=requiredFteMonths(r,start,end),rate=denominator>0?100*newGapFte/denominator:0;const causes=Object.entries(gapRec.reduce((a,e)=>(a[e.event_type]=(a[e.event_type]||0)+e.newGapFte,a),{}));return{newGapFte,denominator,rate,events:gapRec,causes,onsets:gapRec.filter(e=>e.episodeOnset).length}}
function surveillanceFor(r){if(eventMode==='gated')return null;const w=getWindows(),current=incidenceWindow(r,w.current.start,w.current.end),hist=w.baseline.map(x=>incidenceWindow(r,x.start,x.end)),baseline=hist.length?hist.reduce((a,x)=>a+x.rate,0)/hist.length:0,baselineGap=hist.length?hist.reduce((a,x)=>a+x.newGapFte,0)/hist.length:0,ratio=baseline>0?current.rate/baseline:(current.rate>0?Infinity:0),eligible=requiredFte(r)>=SURVEILLANCE.minRequiredFte;const alert=eligible&&current.newGapFte>0&&(baseline===0?current.newGapFte>=SURVEILLANCE.minNewGapFteWhenBaselineZero:(ratio>=SURVEILLANCE.alertMultiplier&&current.newGapFte>=Math.max(1,baselineGap)));const monitor=eligible&&!alert&&current.rate>baseline&&current.newGapFte>0;return{currentRate:current.rate,baselineRate:baseline,ratio,alert,monitor,currentNewGapFte:current.newGapFte,baselineNewGapFte:baselineGap,denominator:current.denominator,causes:current.causes,histRates:hist.map(x=>x.rate),histGapFte:hist.map(x=>x.newGapFte),onsets:current.onsets,window:w.current}}
function signalState(r){const s=surveillanceFor(r);return!s?'gated':s.alert?'alert':s.monitor?'monitor':'normal'}
function velocityScore(r){const s=surveillanceFor(r);if(!s)return null;if(s.currentNewGapFte<=0)return 0;if(!Number.isFinite(s.ratio))return Math.min(100,45+15*s.currentNewGapFte);if(s.ratio<=1)return Math.round(30*Math.max(0,s.ratio));if(s.ratio<1.5)return Math.round(30+40*(s.ratio-1));return Math.round(Math.min(100,50+(s.ratio-1.5)/1.5*50))}

function currentGapStart(r){if(deficit(r)<=0)return null;const explicit=dUTC(r.gap_onset_date);if(explicit&&explicit<=getAsOfDate())return explicit;const onsets=replayCell(r).records.filter(x=>x.episodeOnset);return onsets.length?dUTC(onsets[onsets.length-1].event_date):null}
function gapAgeDays(r){const d=currentGapStart(r);return d?daysBetween(d,getAsOfDate()):null}
function burdenRaw(r,gapOverride=null,durationDaysOverride=null){const gap=gapOverride==null?deficit(r):Math.max(0,Number(gapOverride)),duration=durationDaysOverride==null?gapAgeDays(r):durationDaysOverride,units=Number(r.service_units_per_gap_fte),crit=Number(r.service_criticality_weight);if(!Number.isFinite(units)||!Number.isFinite(crit)||duration==null)return null;return gap*units*(duration/365)*crit}
function resolvabilityScore(r){const ttf=Number(r.median_time_to_fill_days),scar=Number(r.scarcity_index),subs=Number(r.internal_substitute_fte),gap=Math.max(1,deficit(r));if(![ttf,scar,subs].every(Number.isFinite))return null;const ttfNorm=Math.min(Math.max(ttf,0)/180,1),scarNorm=Math.min(Math.max(scar,0),1),subCover=Math.min(Math.max(subs,0)/gap,1);return Math.round(100*(.45*ttfNorm+.35*scarNorm+.20*(1-subCover)))}
function percentileScore(r,rows,metricFn){const vals=rows.map(x=>({row:x,v:metricFn(x)})).filter(x=>Number.isFinite(x.v)).sort((a,b)=>a.v-b.v);const v=metricFn(r);if(!Number.isFinite(v)||!vals.length)return null;if(vals.length===1)return 50;let below=0,equal=0;for(const x of vals){if(x.v<v)below++;else if(x.v===v)equal++}return Math.round(100*(below+.5*equal)/vals.length)}
function burdenScore(r){return percentileScore(r,SNAPSHOTS.filter(x=>x.sector===r.sector),burdenRaw)}
function decisionPriority(r){const components={velocity:velocityScore(r),burden:burdenScore(r),resolvability:resolvabilityScore(r)};let weights=surveillanceFor(r)?{velocity:.35,burden:.40,resolvability:.25}:{velocity:0,burden:.60,resolvability:.40};let total=0,wSum=0;for(const [k,w] of Object.entries(weights)){if(Number.isFinite(components[k])){total+=components[k]*w;wSum+=w}}const score=wSum?Math.round(total/wSum):null;const full=Number.isFinite(components.burden)&&Number.isFinite(components.resolvability)&&(surveillanceFor(r)?Number.isFinite(components.velocity):false);return{score,components,confidence:full?'full':'preliminary',withinSector:true}}
const priority=r=>decisionPriority(r).score??0;

function sectorSummary(){const rows=currentRows(),needed=rows.reduce((a,r)=>a+requiredFte(r),0),available=rows.reduce((a,r)=>a+availableFte(r),0),matched=rows.reduce((a,r)=>a+Math.min(requiredFte(r),availableFte(r)),0),gap=rows.reduce((a,r)=>a+deficit(r),0),surplusTotal=rows.reduce((a,r)=>a+surplus(r),0),svs=rows.map(surveillanceFor).filter(Boolean),w=getWindows();const aggNewGap=rows.reduce((a,r)=>a+incidenceWindow(r,w.current.start,w.current.end).newGapFte,0),aggDen=rows.reduce((a,r)=>a+requiredFteMonths(r,w.current.start,w.current.end),0),incidenceRate=svs.length===rows.length&&svs.every(s=>s.dataSufficient)&&aggDen>0?100*aggNewGap/aggDen:null,alerts=svs.filter(s=>s.alert).length,monitors=svs.filter(s=>s.monitor).length,high=rows.filter(r=>(decisionPriority(r).score??0)>=70).length,totalBurden=rows.reduce((a,r)=>a+(burdenRaw(r)||0),0);return{rows,needed,available,filled:available,gap,surplus:surplusTotal,coverage:needed?matched/needed:1,rawCoverage:needed?available/needed:1,incidenceRate,newGapFte:aggNewGap,alerts,monitors,high,totalBurden}}
function sectorIncidenceSeries(){const rows=currentRows(),w=getWindows(),windows=[...w.baseline,w.current];return windows.map(win=>{const num=rows.reduce((a,r)=>a+incidenceWindow(r,win.start,win.end).newGapFte,0),den=rows.reduce((a,r)=>a+requiredFteMonths(r,win.start,win.end),0);return den?100*num/den:0})}
function locationPressure(){const cfg=sectorCfg(activeSector);return cfg.locations.map(loc=>{const rows=currentRows().filter(r=>r.location===loc.id),need=rows.reduce((a,r)=>a+requiredFte(r),0),gap=rows.reduce((a,r)=>a+deficit(r),0),maxPriority=rows.length?Math.max(...rows.map(priority)):0;return{id:loc.id,label:loc[lang],need,gap,ratio:need?gap/need:0,maxPriority}}).filter(x=>x.need>0).sort((a,b)=>b.maxPriority-a.maxPriority||b.ratio-a.ratio)}
