import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
import {runInNewContext} from 'node:vm';
import {webcrypto, randomUUID} from 'node:crypto';
const ORIGIN='https://adeebnoor.github.io';
const ts=readFileSync(new URL('../supabase/functions/portfolio-inquiries/index.ts',import.meta.url),'utf8');
const js=stripTypeScriptTypes(ts.replace(/export /g,''),{mode:'strip'})+'\nthis.handler=handler;this.normalize=normalize;';
const valid=()=>({request_id:randomUUID(),kind:'inquiry',language:'en',name:'Audit Test',email:'qa@example.com',audience:'institution',engagement:'advisory',timeline:'quarter',authority:'decision_maker',problem:'This is a clearly labeled synthetic test inquiry.',organization:'Audit',consent:true,website:''});
function setup(fn){const calls=[];const c={Request,Response,Headers,URL,AbortSignal,TextEncoder,TextDecoder,Uint8Array,crypto:webcrypto,Deno:{env:{get:k=>k==='SUPABASE_URL'?'https://example.supabase.co':'server-only-secret'},serve(){}},fetch:async(u,i)=>{calls.push({u,i});return fn?fn(u,i):Response.json({ok:true});}};runInNewContext(js,c);return {...c,calls};}
function request(method='POST',body=valid(),headers={}){return new Request('https://example.supabase.co/functions/v1/portfolio-inquiries',{method,headers:{origin:ORIGIN,'content-type':'application/json',...headers},body:['GET','OPTIONS'].includes(method)?undefined:JSON.stringify(body)});}
test('Qualified request normalizes only approved fields',()=>{const e=setup();const result=e.normalize({...valid(),ownerKey:'must-not-be-stored'});assert.equal(result.ownerKey,undefined);assert.equal(result.consent,true);assert.equal(result.email,'qa@example.com');});
test('Required consent, limits, enumerations and text are enforced',()=>{const e=setup();for(const patch of [{consent:false},{email:'bad'},{name:'a'},{problem:'short'},{problem:'x'.repeat(4001)},{audience:'administrator'},{engagement:'invalid'},{request_id:'bad'},{language:'fr'},{authority:'any'},{organization:'x'.repeat(161)}])assert.equal(e.normalize({...valid(),...patch}),null);});
test('Updates store no accidental private inquiry fields',()=>{const e=setup();const x=e.normalize({...valid(),kind:'updates'});assert.equal(x.problem,undefined);assert.equal(x.audience,undefined);});
test('Cross-origin POST never accesses the database',async()=>{const e=setup();assert.equal((await e.handler(request('POST',valid(),{origin:'https://evil.invalid'}))).status,403);assert.equal(e.calls.length,0);});
test('Missing consent and honeypot never persist',async()=>{const e=setup();assert.equal((await e.handler(request('POST',{...valid(),consent:false}))).status,400);assert.equal((await e.handler(request('POST',{...valid(),website:'bot'}))).status,400);assert.equal(e.calls.length,0);});
test('Oversized body and URL credentials rejected',async()=>{const e=setup();assert.equal((await e.handler(request('POST',{x:'a'.repeat(25000)}))).status,400);assert.equal((await e.handler(new Request('https://example.test/?key=secret'))).status,400);assert.equal(e.calls.length,0);});
test('Public saved request only returns reference; raw IP not persisted',async()=>{const e=setup();const data=valid();const r=await e.handler(request('POST',data,{'x-forwarded-for':'192.0.2.25'}));assert.equal(r.status,200);assert.deepEqual(await r.json(),{ok:true,request_id:data.request_id});assert.equal(e.calls.length,1);const body=JSON.parse(e.calls[0].i.body);assert.match(body.p_ip_bucket,/^ip:[a-f0-9]{64}$/);assert.match(body.p_email_bucket,/^email:[a-f0-9]{64}$/);assert.ok(!JSON.stringify(body).includes('192.0.2.25'));});
test('Rate limits propagate as 429; database failures never claim delivery',async()=>{for(const [response,code]of[[Response.json({ok:false,error:'rate_limited'}),429],[new Response('failed',{status:500}),503]]){const e=setup(()=>response);assert.equal((await e.handler(request())).status,code);}});
test('Private endpoints reject missing key before database access',async()=>{for(const method of ['GET','PATCH','DELETE']){const e=setup();assert.equal((await e.handler(request(method,{}))).status,401);assert.equal(e.calls.length,0);}});
test('Wrong high-entropy key may read only the settings hash',async()=>{const e=setup(()=>Response.json([{admin_key_hash:'0'.repeat(64)}]));const r=await e.handler(request('GET',undefined,{'x-analytics-key':'A'.repeat(43)}));assert.equal(r.status,401);assert.equal(e.calls.length,1);assert.ok(e.calls[0].u.includes('portfolio_analytics_settings'));});
test('Correct owner key unlocks and cleans before bounded read',async()=>{const key='A'.repeat(43);const hash=Buffer.from(await webcrypto.subtle.digest('SHA-256',new TextEncoder().encode(key))).toString('hex');const e=setup(u=>Response.json(u.includes('settings')?[{admin_key_hash:hash}]:u.includes('cleanup')?null:[]));const r=await e.handler(request('GET',undefined,{'x-analytics-key':key}));assert.equal(r.status,200);assert.deepEqual(await r.json(),{items:[]});assert.equal(e.calls.length,3);assert.ok(e.calls[1].u.includes('cleanup'));assert.ok(e.calls[2].u.endsWith('limit=100'));});
test('An owner cannot accidentally patch arbitrary fields or identifiers',async()=>{const key='A'.repeat(43),hash=Buffer.from(await webcrypto.subtle.digest('SHA-256',new TextEncoder().encode(key))).toString('hex');const e=setup(u=>Response.json(u.includes('settings')?[{admin_key_hash:hash}]:null));let r=await e.handler(request('PATCH',{request_id:'anything',status:'closed'},{'x-analytics-key':key}));assert.equal(r.status,400);r=await e.handler(request('PATCH',{request_id:randomUUID(),status:'closed',email:'overwrite@evil.invalid'},{'x-analytics-key':key}));assert.equal(r.status,200);const body=JSON.parse(e.calls.at(-1).i.body);assert.deepEqual(Object.keys(body),['status','updated_at']);});
test('SQL access model is private and consent/rate checks are atomic',()=>{const sql=readFileSync(new URL('../supabase/schema/portfolio-inquiries.sql',import.meta.url),'utf8');assert.ok(sql.includes('enable row level security'));assert.ok(sql.includes('from public, anon, authenticated'));assert.ok(sql.includes('pg_advisory_xact_lock'));assert.ok(sql.includes("interval '180 days'"));assert.ok(!sql.toLowerCase().includes('security definer'));});
